export const GET_IMAGES = 'GET_IMAGES';

export const ADD_IMAGE_TO_CANVAS = 'ADD_IMAGE_TO_CANVAS';

export const DELETE_IMAGE_FROM_CANVAS = 'DELETE_IMAGE_FROM_CANVAS';

export const UPDATE_IMAGE_ORDER = 'UPDATE_IMAGE_ORDER';

export const FILTER_IMAGE = 'FILTER_IMAGE';

export const CHANGE_IMAGE = 'CHANGE_IMAGE';

export const IMAGES_LOADING = 'IMAGES_LOADING';